#!/bin/bash
# vm.sh - PowOS reciprocal VM: boot your *other* installed OS as a VM.
#
# The dual-boot dream without rebooting: from PowOS, run the Windows you
# installed on disk as a KVM guest that boots the SAME physical partition —
# no second copy. (The reverse direction, Windows host → PowOS guest, is
# generated by `powos vm windows-setup`; see docs/DUAL-BOOT-VM.md.)
#
# Entry point: cmd_vm "$@"
#
# SAFETY MODEL (critical — this passes a real disk to a VM):
#   - NEVER boot a disk the host currently has mounted read-write. Booting an OS
#     whose partitions are also live on the host = guaranteed corruption.
#   - Warn loudly if Windows shares a disk with the running PowOS root.
#   - Disable Windows Fast Startup/hibernation first, or the VM boots a frozen
#     image and the on-disk state corrupts.
#   - Nothing launches without an explicit confirmation; --dry-run prints only.
#
# High-perf gaming in the guest needs GPU passthrough (2 GPUs + IOMMU); that is
# an opt-in advanced mode (--gpu), not the default.

set -uo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'

vm_log()  { echo -e "${CYAN}[vm]${NC} $*"; }
vm_ok()   { echo -e "${GREEN}[vm]${NC} $*"; }
vm_warn() { echo -e "${YELLOW}[vm]${NC} $*"; }
vm_err()  { echo -e "${RED}[vm]${NC} $*" >&2; }
vm_step() { echo; echo -e "${BOLD}── $* ──${NC}"; }

# ── Options / globals ─────────────────────────────────────────────
VM_DRY_RUN=0
VM_RAM="8G"
VM_CPUS="4"
VM_GPU=0            # 1 = attempt GPU passthrough (advanced)
VM_DISK=""          # explicit target disk override
VM_OUTPUT="./powos-vm-setup.ps1"   # windows-setup: generated script path

# OVMF (UEFI firmware) search paths — differ across distros.
VM_OVMF_CODE_CANDIDATES=(
    /usr/share/edk2/ovmf/OVMF_CODE.fd
    /usr/share/edk2/x64/OVMF_CODE.4m.fd
    /usr/share/OVMF/OVMF_CODE.fd
    /usr/share/qemu/OVMF_CODE.fd
)
VM_OVMF_VARS_CANDIDATES=(
    /usr/share/edk2/ovmf/OVMF_VARS.fd
    /usr/share/edk2/x64/OVMF_VARS.4m.fd
    /usr/share/OVMF/OVMF_VARS.fd
    /usr/share/qemu/OVMF_VARS.fd
)

vm_find_first_existing() {
    local f
    for f in "$@"; do [[ -f "$f" ]] && { echo "$f"; return 0; }; done
    return 1
}

# ── Disk discovery ────────────────────────────────────────────────
# Which physical disk backs the running PowOS root? Never boot that one.
vm_host_root_disk() {
    local src base
    src=$(findmnt -n -o SOURCE / 2>/dev/null || true)
    [[ -z "$src" ]] && return 0
    base=$(lsblk -no PKNAME "$src" 2>/dev/null | head -1)
    [[ -n "$base" ]] && echo "/dev/$base"
}

# Find the disk that holds a Windows install (Boot Manager or NTFS).
# Echoes the disk path, returns 0 if found.
vm_find_windows_disk() {
    local disk part
    while read -r disk; do
        [[ -b "$disk" ]] || continue
        while read -r part; do
            [[ -b "$part" ]] || continue
            local fstype; fstype=$(blkid -o value -s TYPE "$part" 2>/dev/null || true)
            if [[ "$fstype" == "ntfs" ]]; then echo "$disk"; return 0; fi
            if [[ "$fstype" == "vfat" ]]; then
                local mp; mp=$(mktemp -d)
                if mount -o ro "$part" "$mp" 2>/dev/null; then
                    if [[ -e "$mp/EFI/Microsoft/Boot/bootmgfw.efi" ]]; then
                        umount "$mp" 2>/dev/null; rmdir "$mp" 2>/dev/null
                        echo "$disk"; return 0
                    fi
                    umount "$mp" 2>/dev/null || true
                fi
                rmdir "$mp" 2>/dev/null || true
            fi
        done < <(lsblk -ln -o PATH "$disk" 2>/dev/null | tail -n +2)
    done < <(lsblk -dn -o PATH,TYPE 2>/dev/null | awk '$2=="disk"{print $1}')
    return 1
}

# Is any partition of $1 currently mounted on the host?
vm_disk_is_mounted() {
    local disk="$1" part
    while read -r part; do
        findmnt -n -S "$part" &>/dev/null && return 0
    done < <(lsblk -ln -o PATH "$disk" 2>/dev/null | tail -n +2)
    return 1
}

# ── Launch config generation (pure — unit-testable) ───────────────
# Emit a qemu-system-x86_64 command line for booting $disk as a UEFI guest.
# Uses AHCI/SATA (native Windows driver support) for the passed-through disk.
vm_build_qemu_cmd() {
    local disk="$1" ram="$2" cpus="$3" ovmf_code="$4" ovmf_vars="$5" gpu="${6:-0}"
    local -a cmd=(
        qemu-system-x86_64
        -enable-kvm
        -machine "q35,smm=on"
        -cpu host
        -smp "$cpus"
        -m "$ram"
        -drive "if=pflash,format=raw,readonly=on,file=${ovmf_code}"
        -drive "if=pflash,format=raw,file=${ovmf_vars}"
        -drive "file=${disk},format=raw,if=none,id=osdisk,cache=none,aio=native"
        -device "ahci,id=ahci"
        -device "ide-hd,drive=osdisk,bus=ahci.0"
        -netdev "user,id=net0"
        -device "virtio-net-pci,netdev=net0"
        -usb -device usb-tablet
    )
    if [[ "$gpu" == "1" ]]; then
        # Real passthrough: hand every PCI function on the dGPU's slot (GPU + its
        # HDMI-audio, e.g. 01:00.0 + 01:00.1) to the guest. The functions must
        # already be bound to vfio-pci ('powos gpu to-vm', done at launch time).
        local _dgpu _slot _bdf
        _dgpu=$(lspci -Dn | awk '$2=="0300:" && $3 ~ /^10de:/{print $1; exit}')
        _slot="${_dgpu%.*}."
        for _bdf in $(lspci -Dn | awk -v s="$_slot" 'index($1,s)==1{print $1}'); do
            cmd+=( -device "vfio-pci,host=${_bdf#0000:}" )
        done
    else
        cmd+=( -display "gtk,gl=on" -device virtio-vga-gl )
    fi
    # Plain space-join: these args contain no spaces, so this stays eval-safe
    # while remaining readable (unlike %q, which backslash-escapes the commas).
    printf '%s ' "${cmd[@]}"
    echo
}

# ── powos vm windows ──────────────────────────────────────────────
vm_windows() {
    vm_step "Boot installed Windows as a VM"

    local disk="$VM_DISK"
    if [[ -z "$disk" ]]; then
        disk=$(vm_find_windows_disk) || {
            vm_err "No Windows install found on any disk."
            vm_err "Install Windows first, or pass --disk /dev/sdX explicitly."
            return 1
        }
    fi
    vm_log "Windows disk: $disk"

    # Safety: never boot a disk the host has mounted.
    if vm_disk_is_mounted "$disk"; then
        vm_err "$disk has partitions mounted on the host RIGHT NOW."
        vm_err "Booting it in a VM would corrupt the filesystem. Unmount them first."
        return 1
    fi

    # Safety: warn if Windows shares the disk with the running PowOS root.
    local root_disk; root_disk=$(vm_host_root_disk)
    if [[ -n "$root_disk" && "$disk" == "$root_disk" ]]; then
        vm_warn "$disk also holds the running PowOS root. The VM will have"
        vm_warn "write access to the whole disk — including your Linux partitions."
        vm_warn "Prefer Windows on a separate disk. Proceed only if you understand this."
    fi

    # Firmware
    local ovmf_code ovmf_vars
    ovmf_code=$(vm_find_first_existing "${VM_OVMF_CODE_CANDIDATES[@]}") || {
        vm_err "OVMF UEFI firmware not found. Install edk2-ovmf (dnf install edk2-ovmf)."
        return 1
    }
    local src_vars
    src_vars=$(vm_find_first_existing "${VM_OVMF_VARS_CANDIDATES[@]}") || {
        vm_err "OVMF_VARS template not found (edk2-ovmf)."; return 1
    }
    # Per-VM writable NVRAM copy.
    local vars_dir="${XDG_STATE_HOME:-$HOME/.local/state}/powos/vm"
    ovmf_vars="${vars_dir}/windows_VARS.fd"

    local cmd
    cmd=$(vm_build_qemu_cmd "$disk" "$VM_RAM" "$VM_CPUS" "$ovmf_code" "$ovmf_vars" "$VM_GPU")

    vm_step "Plan"
    echo "  Disk (passthrough): $disk"
    echo "  RAM / vCPUs:        $VM_RAM / $VM_CPUS"
    echo "  Firmware:           $ovmf_code"
    echo "  NVRAM (writable):   $ovmf_vars"
    echo "  GPU passthrough:    $([[ $VM_GPU == 1 ]] && echo 'yes (needs vfio-pci + IOMMU)' || echo 'no (virtio-vga)')"
    echo
    echo -e "  ${DIM}$cmd${NC}"
    echo
    echo -e "  ${BOLD}Before first boot:${NC} in Windows, disable Fast Startup + hibernation"
    echo "    (powercfg.exe /hibernate off). Windows may re-check activation because"
    echo "    the VM looks like different hardware — a digital licence absorbs this."

    if [[ $VM_DRY_RUN -eq 1 ]]; then
        vm_warn "--dry-run: not launching."
        return 0
    fi

    echo
    read -r -p "Launch the Windows VM now? [y/N] " ans
    [[ "$ans" =~ ^[Yy]$ ]] || { vm_log "Aborted."; return 0; }

    if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
        vm_err "Booting a raw disk needs root. Re-run: sudo powos vm windows"
        return 1
    fi
    if ! command -v qemu-system-x86_64 &>/dev/null; then
        vm_err "qemu not installed. Install qemu-kvm (dnf install qemu-kvm edk2-ovmf)."
        return 1
    fi
    mkdir -p "$vars_dir"
    [[ -f "$ovmf_vars" ]] || cp "$src_vars" "$ovmf_vars"

    if [[ "$VM_GPU" == 1 ]]; then
        vm_step "Hotswapping the dGPU to the VM (powos gpu to-vm)"
        powos gpu to-vm || { vm_err "GPU hotswap failed — see 'powos gpu status'. Aborting."; return 1; }
    fi

    vm_ok "Launching Windows VM…"
    eval "$cmd"
    local vmrc=$?

    if [[ "$VM_GPU" == 1 ]]; then
        vm_step "Reclaiming the dGPU for the host (powos gpu to-host)"
        powos gpu to-host || vm_warn "Couldn't auto-reclaim — run 'powos gpu to-host' manually."
    fi
    return $vmrc
}

# ── Windows-setup script generation (pure — unit-testable) ────────
# Emit the Windows-side PowerShell script that boots THIS PowOS install as a
# VirtualBox guest via a raw-disk VMDK (Direction B in docs/DUAL-BOOT-VM.md).
# Pure: no discovery, no filesystem writes — just prints the script.
#
# Args: $1 = GPT disk GUID (Linux PTUUID; empty = MBR disk → fall back to
#            size+model matching with a manual-verification warning)
#       $2 = disk model   $3 = disk size in bytes   $4 = VM name (def. PowOS)
#
# The generated script must stay plain-ASCII Windows PowerShell 5.1
# (no ternary, no &&, no ${Env:} braces). Placeholders (__POWOS_*__) are
# substituted with bash parameter expansion — never sed.
vm_build_windows_setup_ps1() {
    local guid="$1" model="$2" size_bytes="$3" vm_name="${4:-PowOS}"
    # Keep the model safe inside PS single-quoted strings.
    model="${model//\'/}"; model="${model//\`/}"

    local locate header_guid
    if [[ -n "$guid" ]]; then
        header_guid="$guid"
        locate=$(cat <<'PSEOF'
# Locate the PowOS disk by its GPT disk GUID. On a GPT disk, the Linux
# PTUUID (blkid -o value -s PTUUID /dev/sdX) is the same identifier that
# Windows exposes as (Get-Disk).Guid -- Windows just wraps it in braces.
# String -eq in PowerShell is case-insensitive, so letter case is irrelevant.
$target = '{__POWOS_GUID__}'
$found = @(Get-Disk | Where-Object { ('' + $_.Guid) -eq $target })
if ($found.Count -eq 0) {
    Write-Host ('ERROR: no disk with GUID ' + $target + ' was found.')
    Write-Host 'Is the PowOS disk connected? Inspect disks with:'
    Write-Host '  Get-Disk | Format-List Number, FriendlyName, Size, Guid'
    exit 1
}
if ($found.Count -gt 1) {
    Write-Host ('ERROR: ' + $found.Count + ' disks match GUID ' + $target + ' - refusing to guess.')
    exit 1
}
$Disk = $found[0]
PSEOF
)
    else
        header_guid="(none - MBR partition table)"
        locate=$(cat <<'PSEOF'
# !!! MANUAL VERIFICATION REQUIRED !!!
# The PowOS disk has an MBR partition table, so it has no GPT disk GUID.
# This script falls back to matching by SIZE and MODEL, which is NOT a
# unique identifier. VERIFY the disk number printed below against
# Disk Management (diskmgmt.msc) BEFORE typing YES.
# Selecting the wrong disk risks destroying data on it.
$targetModel = '__POWOS_MODEL__'
$targetBytes = __POWOS_SIZE_BYTES__
$found = @(Get-Disk | Where-Object { $_.Size -eq $targetBytes -and (('' + $_.FriendlyName) -like ('*' + $targetModel + '*')) })
if ($found.Count -eq 0) {
    Write-Host ('ERROR: no disk matching model "' + $targetModel + '" with size ' + $targetBytes + ' bytes was found.')
    Write-Host 'Inspect disks with: Get-Disk | Format-List Number, FriendlyName, Size'
    exit 1
}
if ($found.Count -gt 1) {
    Write-Host ('ERROR: ' + $found.Count + ' disks match by size+model - refusing to guess.')
    Write-Host 'Identify the right disk in Disk Management, then edit this script'
    Write-Host 'to select it explicitly: $Disk = Get-Disk -Number N'
    exit 1
}
$Disk = $found[0]
PSEOF
)
    fi

    local script
    script=$(cat <<'PSEOF'
#Requires -RunAsAdministrator
# powos-vm-setup.ps1 -- boot your on-disk PowOS install as a VirtualBox VM.
# Generated by: powos vm windows-setup (re-run it to regenerate)
#
# Target PowOS disk (as seen from Linux at generation time):
#   Model:         __POWOS_MODEL__
#   Size (bytes):  __POWOS_SIZE_BYTES__
#   GPT disk GUID: __POWOS_HEADER_GUID__
#   (the Linux PTUUID of a GPT disk == the Windows (Get-Disk).Guid)
#
# Windows PowerShell 5.1 compatible. Run from an elevated PowerShell:
#   powershell -ExecutionPolicy Bypass -File .\powos-vm-setup.ps1
#
# SAFETY: never boot the resulting VM while Windows has any of the PowOS
# disk partitions mounted or in use -- that corrupts the filesystem.

$ErrorActionPreference = 'Stop'
$VmName = '__POWOS_VM_NAME__'

Write-Host '== PowOS VM setup (VirtualBox raw-disk) =='
Write-Host ''

__POWOS_LOCATE__

Write-Host 'Found the PowOS disk:'
Write-Host ('  Number : ' + $Disk.Number)
Write-Host ('  Model  : ' + $Disk.FriendlyName)
Write-Host ('  Size   : ' + [math]::Round($Disk.Size / 1GB, 1) + ' GB')
Write-Host ''
Write-Host 'This disk will be attached RAW to a VirtualBox VM. The VM gets'
Write-Host 'full write access to the whole physical disk.'
$answer = Read-Host 'Type YES (uppercase) to continue'
if ($answer -cne 'YES') {
    Write-Host 'Aborted - nothing was changed.'
    exit 1
}

# Find VBoxManage (PATH first, then the default install location).
$VBoxManage = $null
$cmd = Get-Command VBoxManage.exe -ErrorAction SilentlyContinue
if ($cmd) { $VBoxManage = $cmd.Source }
if (-not $VBoxManage) {
    $candidate = Join-Path $Env:ProgramFiles 'Oracle\VirtualBox\VBoxManage.exe'
    if (Test-Path $candidate) { $VBoxManage = $candidate }
}
if (-not $VBoxManage) {
    Write-Host 'ERROR: VBoxManage.exe not found.'
    Write-Host 'Install VirtualBox first: https://www.virtualbox.org/wiki/Downloads'
    Write-Host '  (or: winget install Oracle.VirtualBox)'
    Write-Host 'Then re-run this script.'
    exit 1
}
Write-Host ('Using VBoxManage: ' + $VBoxManage)

# 1. Raw-disk VMDK wrapper (no data is copied; the VMDK points at the disk).
$Vmdk = Join-Path (Get-Location) 'powos.vmdk'
$RawDisk = '\\.\PhysicalDrive' + $Disk.Number
Write-Host ('Creating raw VMDK: ' + $Vmdk + ' -> ' + $RawDisk)
& $VBoxManage internalcommands createrawvmdk -filename $Vmdk -rawdisk $RawDisk
if ($LASTEXITCODE -ne 0) { Write-Host 'ERROR: createrawvmdk failed.'; exit 1 }

# 2. Create + configure the VM (UEFI firmware -- PowOS boots via UEFI).
& $VBoxManage createvm --name $VmName --ostype Fedora_64 --register
if ($LASTEXITCODE -ne 0) { Write-Host 'ERROR: createvm failed.'; exit 1 }
& $VBoxManage modifyvm $VmName --firmware efi --memory 8192 --cpus 4 --nic1 nat
if ($LASTEXITCODE -ne 0) { Write-Host 'ERROR: modifyvm failed.'; exit 1 }
& $VBoxManage storagectl $VmName --name 'SATA' --add sata --controller IntelAhci
if ($LASTEXITCODE -ne 0) { Write-Host 'ERROR: storagectl failed.'; exit 1 }
& $VBoxManage storageattach $VmName --storagectl 'SATA' --port 0 --device 0 --type hdd --medium $Vmdk
if ($LASTEXITCODE -ne 0) { Write-Host 'ERROR: storageattach failed.'; exit 1 }

Write-Host ''
Write-Host '== Done =='
Write-Host ('Start the VM with:  VBoxManage startvm ' + $VmName)
Write-Host '(VirtualBox must run elevated to open a raw physical disk.)'
Write-Host ''
Write-Host 'Safety notes:'
Write-Host ' - NEVER boot this VM while Windows has any of the PowOS disk'
Write-Host '   partitions mounted or otherwise in use (guaranteed corruption).'
Write-Host ' - PowOS detects the VM and applies its "virtual" hardware profile'
Write-Host '   automatically - no reconfiguration needed inside the guest.'
PSEOF
)

    # Substitute locate block first (it carries its own placeholders).
    script=${script//__POWOS_LOCATE__/$locate}
    script=${script//__POWOS_GUID__/$guid}
    script=${script//__POWOS_HEADER_GUID__/$header_guid}
    script=${script//__POWOS_MODEL__/$model}
    script=${script//__POWOS_SIZE_BYTES__/$size_bytes}
    script=${script//__POWOS_VM_NAME__/$vm_name}
    printf '%s\n' "$script"
}

# ── powos vm windows-setup ────────────────────────────────────────
# Discovery + file write around the pure generator above.
vm_windows_setup() {
    vm_step "Generate Windows-side setup for booting PowOS as a VM"

    # 1. Identify the PowOS disk: --disk wins; else the disk holding the
    #    POWOS-DATA partition; else the disk backing the root filesystem.
    local disk="$VM_DISK" how="--disk override"
    if [[ -z "$disk" ]]; then
        local part
        part=$(blkid -L POWOS-DATA 2>/dev/null || true)
        if [[ -n "$part" ]]; then
            local pk; pk=$(lsblk -no PKNAME "$part" 2>/dev/null | head -1)
            [[ -n "$pk" ]] && { disk="/dev/$pk"; how="holds POWOS-DATA"; }
        fi
    fi
    if [[ -z "$disk" ]]; then
        disk=$(vm_host_root_disk); how="backs the root filesystem"
        [[ -n "$disk" ]] && vm_warn "POWOS-DATA partition not found; falling back to the root disk."
    fi
    if [[ -z "$disk" ]]; then
        vm_err "Could not identify the PowOS disk: no POWOS-DATA partition found"
        vm_err "and the root filesystem's disk could not be resolved."
        vm_err "Pass it explicitly: powos vm windows-setup --disk /dev/sdX"
        return 1
    fi
    if [[ ! -b "$disk" ]]; then
        vm_err "$disk is not a block device. Pass a whole disk (e.g. /dev/nvme0n1)."
        return 1
    fi
    vm_log "PowOS disk: $disk ($how)"

    # 2. Collect disk facts. For GPT, PTUUID is the disk GUID that Windows
    #    exposes as (Get-Disk).Guid. For MBR, PTUUID is only a 32-bit disk
    #    signature — useless as a GUID — so treat it as absent.
    local guid pttype model size_bytes size_h
    pttype=$(blkid -o value -s PTTYPE "$disk" 2>/dev/null || true)
    guid=$(blkid -o value -s PTUUID "$disk" 2>/dev/null || true)
    if [[ "$pttype" != "gpt" ]]; then
        guid=""
    fi
    model=$(lsblk -dno MODEL "$disk" 2>/dev/null | head -1 | tr -d '\r')
    model="${model#"${model%%[![:space:]]*}"}"   # trim leading whitespace
    model="${model%"${model##*[![:space:]]}"}"   # trim trailing whitespace
    [[ -z "$model" ]] && model="unknown"
    size_bytes=$(lsblk -bdno SIZE "$disk" 2>/dev/null | head -1)
    size_bytes="${size_bytes//[[:space:]]/}"
    [[ -z "$size_bytes" ]] && size_bytes=0
    size_h=$(lsblk -dno SIZE "$disk" 2>/dev/null | head -1)
    size_h="${size_h//[[:space:]]/}"

    if [[ -z "$guid" ]]; then
        vm_warn "$disk has no GPT disk GUID (partition table: ${pttype:-unknown})."
        vm_warn "The generated script will match by size+model instead and demand"
        vm_warn "manual verification of the disk number before doing anything."
    fi

    vm_step "Plan"
    echo "  Disk:       $disk ($how)"
    echo "  Model:      $model"
    echo "  Size:       ${size_h:-?} (${size_bytes} bytes)"
    echo "  Disk GUID:  ${guid:-none — MBR fallback: size+model matching}"
    echo "  VM name:    PowOS"
    echo "  Output:     $VM_OUTPUT"

    local script
    script=$(vm_build_windows_setup_ps1 "$guid" "$model" "$size_bytes" "PowOS")

    if [[ $VM_DRY_RUN -eq 1 ]]; then
        echo
        vm_warn "--dry-run: printing the script, writing nothing."
        echo
        printf '%s\n' "$script"
        return 0
    fi

    if ! printf '%s\n' "$script" > "$VM_OUTPUT"; then
        vm_err "Failed to write $VM_OUTPUT"
        return 1
    fi
    vm_ok "Wrote $VM_OUTPUT"
    echo
    echo -e "  ${BOLD}Next steps (on the Windows machine):${NC}"
    echo "    1. Copy $(basename "$VM_OUTPUT") over (USB, network share, ...)"
    echo "    2. Run it from an elevated PowerShell:"
    echo "         powershell -ExecutionPolicy Bypass -File .\\$(basename "$VM_OUTPUT")"
    echo "    3. It locates the disk, shows what it found, and asks you to type"
    echo "       YES before creating the raw VMDK + VirtualBox VM."
    echo "    4. Start it with: VBoxManage startvm PowOS"
    echo
    echo -e "  ${BOLD}Safety:${NC} never boot the VM while Windows has any of this disk's"
    echo "  partitions mounted or in use. PowOS detects the VM and applies the"
    echo "  'virtual' hardware profile automatically."
}

# ── powos vm status ───────────────────────────────────────────────
vm_status() {
    vm_step "Bootable-as-VM operating systems"
    local root_disk; root_disk=$(vm_host_root_disk)
    echo "  Running PowOS root disk: ${root_disk:-unknown} (never bootable as a VM)"
    echo
    local wdisk
    if wdisk=$(vm_find_windows_disk); then
        local mounted="no"; vm_disk_is_mounted "$wdisk" && mounted="YES (unmount before booting)"
        echo -e "  Windows:  ${GREEN}found${NC} on $wdisk"
        echo "            mounted on host: $mounted"
        echo "            boot it with:    sudo powos vm windows"
    else
        echo "  Windows:  not found on any disk"
    fi
    echo
    echo -e "  ${DIM}Reverse direction (Windows host → PowOS guest): generate the${NC}"
    echo -e "  ${DIM}Windows-side script with 'sudo powos vm windows-setup'${NC}"
    echo -e "  ${DIM}(details: docs/DUAL-BOOT-VM.md, Direction B)${NC}"
}

vm_usage() {
    cat << EOF
powos vm — boot your other installed OS as a VM (no reboot, same partition)

Usage: powos vm <command> [options]

Commands:
  status            Show which installed OSes can be booted as a VM
  windows           Boot the installed Windows as a KVM guest (needs root)
  windows-setup     Generate a PowerShell script that lets Windows boot THIS
                    PowOS install as a VirtualBox VM (raw disk, Direction B)

Options (for 'windows'):
  --dry-run         Print the plan + qemu command, launch nothing
  --disk /dev/sdX   Use this disk instead of auto-detecting Windows
  --ram SIZE        Guest RAM (default: $VM_RAM)
  --cpus N          Guest vCPUs (default: $VM_CPUS)
  --gpu             Attempt GPU passthrough (advanced: needs 2 GPUs + IOMMU)
  -h, --help        This help

Options (for 'windows-setup'):
  --dry-run         Print the generated PowerShell script, write nothing
  --disk /dev/sdX   Use this disk instead of auto-detecting the PowOS disk
  --output FILE     Where to write the script (default: $VM_OUTPUT)

Safety: never boots a disk mounted on the host; warns if Windows shares the
PowOS disk; nothing launches without confirmation. Disable Windows Fast Startup
first. Reverse direction (run PowOS from Windows) is in docs/DUAL-BOOT-VM.md.
EOF
}

cmd_vm() {
    local sub="${1:-status}"; shift 2>/dev/null || true
    # Parse options (order-independent).
    local args=()
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run) VM_DRY_RUN=1; shift ;;
            --gpu)     VM_GPU=1; shift ;;
            --disk)    VM_DISK="${2:-}"; shift 2 ;;
            --ram)     VM_RAM="${2:-8G}"; shift 2 ;;
            --cpus)    VM_CPUS="${2:-4}"; shift 2 ;;
            --output)  VM_OUTPUT="${2:-$VM_OUTPUT}"; shift 2 ;;
            -h|--help) vm_usage; return 0 ;;
            *)         args+=("$1"); shift ;;
        esac
    done
    case "$sub" in
        status|list)     vm_status ;;
        windows|win)     vm_windows ;;
        windows-setup|winsetup) vm_windows_setup ;;
        help|-h|--help)  vm_usage ;;
        *)               vm_err "Unknown vm command: $sub"; vm_usage; return 1 ;;
    esac
}
